version: '3.1'

services:
  minijira-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - minijira-network

networks:
  minijira-network: